### ISSUE TITLE
supreme-umbrella

### ISSUE THREAD

**Issue by Yvees** [clawit/workload#5]
- [x] 微信验证接口
- [x] 微信自动回复接口
- [x] 微信自定义菜单
- [x] 新增一个creator页面
- [x] js发起创建房间请求
- [x] 创建房间接口，有游戏则直接加入，没有则创建一个新的
- [x] mc sdk更新异步方式
- [ ] 增加一个等待游戏开始wait页面,需要有一个开始游戏按钮
- [x] mc server需要增加一个开始游戏判断，只有开房的人才能开始
- [x] mc server需要增加一个回调入口，在游戏结束后调用积分接口
- [x] 增加积分逻辑接口
- [x] 一局结束要记下比分结果
- [x] 一局结束要有个结束页面
